### ISSUE TITLE
"Jinxes" link is dead

### ISSUE THREAD

**Issue by tseel** [ryanascherr/botc#1]
Links to https://cdn.discordapp.com/attachments/696695228496871436/1121544534896164985/jinx_rules_v3.png, which I assume is meant to be the picture of all the jinxes, but it's dead
![image](https://github.com/ryanascherr/botc/assets/25331987/5585b4b2-6565-440a-8200-1791e29b14a9)

**Comment by ryanascherr** [comment]
Thanks for the find! Just updated it so that the link now leads to the official jinx page.
