### ISSUE TITLE
Missing Characters

### ISSUE THREAD

**Issue by Spirit0Raven** [ryanascherr/botc#3]
I apologize if this isn't the proper outlet to do this, but BOTC has since released new characters, such as the Zealot and the Lord of Typhon, and they are yet to be added.

**Comment by ryanascherr** [comment]
This is a great outlet for feedback! I've been busy lately and have forgotten to update - thanks for the reminder. I've just added Zealot and Lord Of Typhon, as well as recent changelog updates.
